### PR TITLE
Update ecdsa_secp256k1.nr with a `test`

### PR DESCRIPTION
**Pull request by skaunov**
Greetings!

I feel like this test should pass, but it fails! Could you, pls, indicate the cause of failure? Maybe I just got something wrong. =(

### CODE REVIEW

**Comment by shuklaayush** [comment]
The points are represented as [jacobian coordinates](https://en.wikibooks.org/wiki/Cryptography/Prime_Curve/Jacobian_Coordinates) and not usual projective coordinates.

You can check that it works if you change it to this 
```rust
    let g_projective_z_doubled = Point{
        x: curve.gen.x.mul(two).mul(two),
        y: curve.gen.y.mul(two).mul(two).mul(two),
        z: two,
    };

```

**Comment by skaunov** [comment]
Thank you for the link and sorry for bothering!

Should I just close the PR or is it better to add a corrected version of the test that you posted so that future reader won't fall into the same misunderstanding?

**Comment by shuklaayush** [comment]
We can add a test. Can you fix it?

**Comment by skaunov** [comment]
yeah, of course
I'll update this one!

**Pull request merged**
